### ISSUE TITLE
make setup-apps not working. Error described

### ISSUE THREAD

**Issue by Mishul-G** [rubykube/peatio-workbench#20]
`== Preparing database ==
rails aborted!
Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application/configuration.rb:139:in `database_configuration'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railtie.rb:34:in `block (3 levels) in <class:Railtie>'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:6:in `require'
bin/rails:6:in `<main>'

Caused by:
Could not load database configuration. No such file - ["config/database.yml"]
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/application/configuration.rb:139:in `database_configuration'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railtie.rb:34:in `block (3 levels) in <class:Railtie>'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:6:in `require'
bin/rails:6:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
make: *** [setup-apps] Error 1
`

I get the above issue when I run "make setup-apps". I fail to see why this is occurring time and again.

**Comment by nchigwamba** [comment]
I had to rename barong/config/database.yml.example to barong/config/database.yml. Note, I am just using the software for non-production use so you might need further expert advise.

**Comment by Mishul-G** [comment]
Thank you @nchigwamba! I upgraded my ruby and did what you mentioned, and got over this hurdle.
