### ISSUE TITLE
Cannot sign into barong:8001

### ISSUE THREAD

**Issue by Mishul-G** [rubykube/peatio-workbench#21]
I have successfully come to the step to where I need to go to "barong:8001" and sign in. For email, I am using "admin@barong.io" and for the password I am using the credentials generated via "docker-compose run --rm barong bin/rake db:seed"

When I input these into "barong:8001", I get the message "Invalid email or password". I need to do this so I can create the new application.

Furthermore, in docker-compose.yaml, I will input the credentials found above?

Also, what port of the local server do I access once I finish the last few steps? It just says start your local server. Confusing guide

**Comment by tigwyk** [comment]
I'm also getting this problem. The admin credentials it spits out look like a hash of some sort. But using that as the password with "admin@barong.io" always comes back with invalid email/password.

**Comment by nchigwamba** [comment]
I ran into a similar problem. However, after running `make setup-apps`, the admin credentials are also listed as one of the last lines printed. I used that "hash" and it worked.

**Comment by Mishul-G** [comment]
@nchigwamba Thanks, this password ended up working for me. Currently, I am trying to verify my phone and am not getting texts to verify and move further.. How do you go about that which is not listed in the guide? Thanks alot for your help.

Could we chat on another platform? I would really appreciate your help.

**Comment by Mishul-G** [comment]
For Everyone, you don't need to verify your phone. You can just click on the applications link once u sign in.

**Comment by nchigwamba** [comment]
@Mishul-G Ping me via n.chigwamba@plusfourx.com, then we can chat further.

**Comment by Mishul-G** [comment]
@nchigwamba Thanks for giving me your info. I have emailed you, looking forward to hear back from you. Have a meeting with few VC's early in the week, would really appreciate a quick reply. Thanks a lot!
